[env]
build_src_flags =
    -Wall -Wextra -Werror=return-type
; Overrides -Og and removes debugging symbols
; Otherwise builds are not deterministic and results in OS-dependent hashes
debug_build_flags = -Os
monitor_speed = 115200

; Freeze package versions
platform_packages =
    ; STM32
    platformio/framework-stm32cubef4@^1.26.2
    platformio/framework-cmsis-stm32f4@^2.6.4
    platformio/framework-stm32cubef1@^1.8.6
    platformio/framework-cmsis-stm32f1@^4.3.1
    platformio/framework-stm32cubeg4@^1.6.1
    tool-dfuutil@1.11.0
    tool-ldscripts-ststm32@0.2.0
    tool-openocd@2.1100.211028
    toolchain-gccarmnoneeabi@1.70201.0

[debug]
build_type = debug

[release]
build_type = release

; Device configurations

[STM32F103C8T6]
platform = ststm32
board = generic_f103c8
framework = stm32cube
upload_protocol = stlink

; =========================
; STM32G474QET6
; =========================
[STM32G474QET6]
platform = ststm32
board = nucleo_g474re
framework = stm32cube
upload_protocol = stlink

; Test
[DeviceF1]
extends = STM32F103C8T6
monitor_speed = 115200
build_flags =
    ${env.build_flags}
    -I include/Test
    -I include/Test/USB


[env:DeviceF1_debug]
extends = DeviceF1, debug

[env:DeviceF1_release]
extends = DeviceF1, release

[DeviceG4]
extends = STM32G474QET6
monitor_speed = 115200
build_flags =
    ${env.build_flags}
    -I include/Test
    -I include/Test/USB
    -D HSE_VALUE=8000000UL
    
src_filter =
    +<*>


[env:DeviceG4_debug]
extends = DeviceG4, debug

[env:DeviceG4_release]
extends = DeviceG4, release